import std/core;

func foo() -> Result!<void, Error> {
	return Ok();
}

func main() -> void {
	assert(foo() is Ok);
}
